sudo: required
services:
  - docker
script:
  - docker build -t front1 .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag front1 $DOCKER_USER/front1:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/front1:$TRAVIS_BUILD_NUMBER
  - docker tag front1 $DOCKER_USER/front1:latest
  - docker push $DOCKER_USER/front1:latest